[project]
name = "git-pulsar"
version = "0.16.0"
description = "Automated, paranoid git backups for students and casual coding."
readme = "README.md"
authors = [
    { email = "jackson.ferguson0@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "argcomplete>=3.7.2",
    "rich>=14.2.0",
]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Repository = "https://github.com/jacksonfergusondev/git-pulsar"
Issues = "https://github.com/jacksonfergusondev/git-pulsar/issues"
PyPi = "https://pypi.org/project/git-pulsar/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
    "/demo",
    "/branding",
    "/scripts",
]

[project.scripts]
git-pulsar = "git_pulsar.cli:main"
git-pulsar-daemon = "git_pulsar.daemon:main"

[dependency-groups]
dev = [
    "hypothesis>=6.150.2",
    "mypy>=1.19.1",
    "prek>=0.4.14",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.13",
]

# ==================================================
# Tool Configuration
# ==================================================

# ---- ruff ---- #

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "D",   # pydocstyle
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "PT",  # flake8-pytest
    "RET", # flake8-return
    "RUF", # Ruff-specific
    "SIM", # flake8-simplify
    "T20", # flake8-print
    "UP",  # pyupgrade
]
ignore = ["D100", "D104", "D107", "E501"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["git_pulsar"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["T201", "D"]
"scripts/*.py" = ["T201"]

# ---- mypy ---- #

[tool.mypy]
mypy_path = "src"
python_version = "3.12"
strict=true
pretty = true
show_error_codes = true
show_error_context = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_calls = false
warn_return_any = false

# ---- pytest ---- #

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = ["tests"]
pythonpath = ["."]

[tool.coverage.run]
source = ["src/git_pulsar"]
omit = ["src/git_pulsar/service.py"]
branch = true

[tool.coverage.report]
omit = ["src/git_pulsar/**/__init__.py"]
show_missing = true
skip_covered = true
fail_under = 75
