blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/jacksonfergusondev/git-pulsar/discussions
    about: Please ask questions and discuss ideas here before opening an issue.
