import shutil
import sys
import textwrap
from pathlib import Path

from .constants import BACKUP_BRANCH


def bootstrap_env() -> None:
    """
    Scaffolds a macOS Python environment: uv, direnv, and VS Code.
    Triggered by `git-pulsar --env`.
    """
    if sys.platform != "darwin":
        print("❌ The --env workflow is currently optimized for macOS.")
        return

    cwd = Path.cwd()
    print(f"⚡ Setting up dev environment in {cwd.name}...")

    # 1. Dependency Check
    missing = []
    if not shutil.which("uv"):
        missing.append("uv")
    if not shutil.which("direnv"):
        missing.append("direnv")

    if missing:
        print(f"❌ Missing tools: {', '.join(missing)}")
        print("   Please run:")
        print(f"     brew install {' '.join(missing)}")
        sys.exit(1)

    # 2. Project Scaffold (uv)
    if not (cwd / "pyproject.toml").exists():
        print("📦 Initializing Python project...")
        # 'uv init' is safe; it creates a standard pyproject.toml
        subprocess.run(["uv", "init", "--no-workspace", "--python", "3.12"], check=True)
    else:
        print("   Existing pyproject.toml found. Skipping init.")

    # 3. Direnv Configuration
    envrc_path = cwd / ".envrc"
    if not envrc_path.exists():
        print("🔌 Creating .envrc...")
        # We use a simplified config that handles the venv creation
        envrc_content = textwrap.dedent("""\
            # Auto-generated by git-pulsar
            if [ ! -d ".venv" ]; then
                echo "Creating virtual environment..."
                uv sync
            fi
            source .venv/bin/activate
            
            source_env_if_exists .envrc.local
        """)
        with open(envrc_path, "w") as f:
            f.write(envrc_content)

        subprocess.run(["direnv", "allow"], check=True)
    else:
        print("   .envrc exists. Skipping.")

    # 4. VS Code Settings (Optimized for Students)
    vscode_dir = cwd / ".vscode"
    settings_path = vscode_dir / "settings.json"

    if not settings_path.exists():
        vscode_dir.mkdir(exist_ok=True)
        print("⚙️  Configuring VS Code...")
        settings_content = textwrap.dedent("""\
            {
                "python.defaultInterpreterPath": ".venv/bin/python",
                "python.terminal.activateEnvironment": true,
                "files.exclude": {
                    "**/__pycache__": true,
                    "**/.ipynb_checkpoints": true,
                    "**/.DS_Store": true,
                    "**/.venv": true
                },
                "search.exclude": {
                    "**/.venv": true
                }
            }
        """)
        with open(settings_path, "w") as f:
            f.write(settings_content)

    print("\n✅ Environment ready.")

    # 5. The "Manual" Hook
    # Check if direnv is likely hooked by checking for the env var it sets
    if "DIRENV_DIR" not in os.environ:
        print("\n👉 Action Required: Enable direnv")
        print("   1. Open your config:")
        print("      code ~/.zshrc  (or nano ~/.zshrc)")
        print("   2. Add this line to the bottom:")
        print('      eval "$(direnv hook zsh)"')
        print("   3. Reload:")
        print("      source ~/.zshrc")


def finalize_work() -> None:
    print("🚀 Finalizing work...")

    # 1. Check we are in a repo
    if not Path(".git").exists():
        print("❌ Not a git repository.")
        sys.exit(1)

    try:
        # 2. Ensure clean working state on current branch (usually wip/pulsar)
        status = subprocess.check_output(
            ["git", "status", "--porcelain"], text=True
        ).strip()
        if status:
            print("⚠️  You have uncommitted changes.")
            print("   Please commit or stash them before finalizing.")
            sys.exit(1)

        # 3. Checkout Main
        print("-> Switching to main...")
        subprocess.run(["git", "checkout", "main"], check=True)

        # 4. Merge Squash
        print(f"-> Squashing {BACKUP_BRANCH}...")
        subprocess.run(["git", "merge", "--squash", BACKUP_BRANCH], check=True)

        # 5. Commit (Interactive)
        print("-> Committing (opens editor)...")
        subprocess.run(["git", "commit"], check=True)

        # 6. Reset Backup Branch
        # We point wip/pulsar to the new main so the next session starts fresh.
        print(f"-> Resetting {BACKUP_BRANCH} to main...")
        subprocess.run(["git", "branch", "-f", BACKUP_BRANCH, "main"], check=True)

        print("\n✅ Work finalized!")
        print(
            f"   You are now on 'main'. "
            f"Run 'git-pulsar' to switch back to {BACKUP_BRANCH}."
        )

    except subprocess.CalledProcessError as e:
        print(f"\n❌ Error during finalize: {e}")
        sys.exit(1)
